using XCALibre
using LinearAlgebra
using Accessors
using Printf
using Statistics

# ==============================================================================
# TUTORIAL: Pore-Scale Homogenisation in XCALibre.jl
# ==============================================================================
# This tutorial demonstrates how to calculate the permeability tensor of a 
# porous medium (a single sphere in a unit cell) using XCALibre.
#
# Methodology:
# 1. Load an OpenFOAM mesh (generated via blockMesh + snappyHexMesh).
# 2. Solve the Stokes Cell Problem in each principal direction (X, Y, Z).
# 3. Apply a unit macroscopic pressure gradient as a source term.
# 4. Calculate the volume-averaged velocity to obtain the Permeability Tensor K.
#
# Comparison with OpenFOAM:
# This script uses the exact same mesh and boundary conditions as the 
# OpenFOAM 'singleSphere' tutorial, allowing for direct performance comparison.
# ==============================================================================

# 1. Setup Mesh & Hardware
# ------------------------------------------------------------------------------
# We load the mesh generated by the OpenFOAM tutorial.
# Make sure you have run the OpenFOAM tutorial first to generate the polyMesh.
mesh_path = "/Volumes/OpenFOAM/comparison/singleSphere/constant/polyMesh"
if !isdir(mesh_path)
    @error "Mesh not found at $mesh_path. Run the OpenFOAM singleSphere Allrun script first."
    exit()
end

@info "Loading Pore-Scale Mesh (Single Sphere)..."
mesh = FOAM3D_mesh(mesh_path)

# Hardware selection (CPU with multithreading)
backend = CPU(); workgroup=1024; activate_multithread(backend)
hardware = Hardware(backend=backend, workgroup=workgroup)
mesh_dev = adapt(backend, mesh)

# 2. Define Physics & Boundary Conditions
# ------------------------------------------------------------------------------
# In periodic homogenisation, we usually apply periodic BCs or
# symmetry/extrapolated BCs if the cell is symmetric.
# Here we match the tutorial BCs: Extrapolated for outer faces, NoSlip for sphere.
BCs = assign(
    (
        U = [
            Extrapolated(:all),
            Wall(:sphere, [0.0, 0.0, 0.0])
        ],
        p = [
            Dirichlet(:all, 0.0),
            Wall(:sphere)
        ]
    ),
    region=mesh_dev
)

# Schemes: Simple Upwind for divergence, Linear for Laplacian (Standard Stokes)
schemes = (U = Schemes(divergence=Upwind), p = Schemes(divergence=Linear))

# Solvers: Iterative solvers with Jacobi preconditioning
solvers = (
    U = SolverSetup(solver=Bicgstab(), preconditioner=Jacobi(), convergence=1e-10, relax=0.9),
    p = SolverSetup(solver=Gmres(), preconditioner=Jacobi(), convergence=1e-10, relax=0.3)
)

config = Configuration(solvers=solvers, schemes=schemes, runtime=Runtime(iterations=500, write_interval=-1, time_step=1.0), hardware=hardware, boundaries=BCs)

# 3. Solver Implementation (Stokes Cell Problem)
# ------------------------------------------------------------------------------
# This function solves for a single direction e_j
function solve_stokes_direction(direction_vector, mesh_dev, BCs, solvers, schemes, config)
    U = VectorField(mesh_dev); initialise!(U, [0.0, 0.0, 0.0])
    p = ScalarField(mesh_dev); initialise!(p, 0.0)
    Uf = FaceVectorField(mesh_dev)
    pf = FaceScalarField(mesh_dev)

    ∇p = Grad{schemes.p.gradient}(p)
    mdotf = FaceScalarField(mesh_dev)
    rDf = FaceScalarField(mesh_dev); initialise!(rDf, 1.0)
    nueff = FaceScalarField(mesh_dev); initialise!(nueff, 1.0) # nu = 1.0
    divHv = ScalarField(mesh_dev)
    
    # Apply macroscopic gradient as an implicit source in momentum
    macro_grad = VectorField(mesh_dev); initialise!(macro_grad, direction_vector)

    U_eqn = (
        Divergence{schemes.U.divergence}(mdotf, U) 
        - Laplacian{schemes.U.laplacian}(nueff, U) 
        == 
        - Source(∇p.result) + Source(macro_grad)
    ) → VectorEquation(U, BCs.U)

    p_eqn = (
        - Laplacian{schemes.p.laplacian}(rDf, p) == - Source(divHv)
    ) → ScalarEquation(p, BCs.p)

    @reset U_eqn.preconditioner = set_preconditioner(solvers.U.preconditioner, U_eqn)
    @reset p_eqn.preconditioner = set_preconditioner(solvers.p.preconditioner, p_eqn)
    @reset U_eqn.solver = XCALibre._workspace(solvers.U.solver, XCALibre._b(U_eqn, XDir()))
    @reset p_eqn.solver = XCALibre._workspace(solvers.p.solver, XCALibre._b(p_eqn))

    Hv = VectorField(mesh_dev)
    rD = ScalarField(mesh_dev)
    xdir, ydir, zdir = XDir(), YDir(), ZDir()

    for iter in 1:config.runtime.iterations
        rx, ry, rz = solve_equation!(U_eqn, U, BCs.U, solvers.U, xdir, ydir, zdir, config)
        
        inverse_diagonal!(rD, U_eqn, config)
        interpolate!(rDf, rD, config)
        remove_pressure_source!(U_eqn, ∇p, config)
        H!(Hv, U, U_eqn, config)
        interpolate!(Uf, Hv, config)
        flux!(mdotf, Uf, config)
        XCALibre.div!(divHv, mdotf, config)
        
        rp = solve_equation!(p_eqn, p, BCs.p, solvers.p, config; ref=0.0)
        grad!(∇p, pf, p, BCs.p, 0.0, config) 
        XCALibre.Solvers.correct_mass_flux!(mdotf, p_eqn, config)
        correct_velocity!(U, Hv, ∇p, rD, config)

        if rx < solvers.U.convergence && rp < solvers.p.convergence
            @printf("  Converged at iteration %d (Res U: %.2e, p: %.2e)\n", iter, rx, rp)
            break
        end
    end
    
    # Volume average velocity for permeability
    return volume_average(U)
end

# 4. Main Execution (Tensor Calculation)
# ------------------------------------------------------------------------------
dim = 3
K = zeros(dim, dim)
@info "Calculating Permeability Tensor K..."

for j in 1:dim
    e_j = zeros(3); e_j[j] = 1.0
    @info "Solving for direction $j ($e_j)..."
    v_avg = solve_stokes_direction(e_j, mesh_dev, BCs, solvers, schemes, config)
    for i in 1:dim
        K[i, j] = v_avg[i]
    end
end

# 5. Output Results
# ------------------------------------------------------------------------------
println("\n" * "="^40)
println("PERMEABILITY TENSOR K:")
display(K)
println("\nSymmetry Residual: ", norm(K - K') / norm(K))
println("="^40)

@info "Tutorial Completed Successfully!"
