# =============================================================================
# Incompressible Stokes L-Bend Benchmark — XCALibre.jl
# =============================================================================
#
# This example solves the standard mixed-form Stokes equations on an L-bend
# geometry imported from an OpenFOAM mesh.
#
# Geometry: L-bend channel (from stokes3plus3_bend OpenFOAM case)
# Parameters: mu = 1.0, f = (1.0, 1.0) to drive both sections of the bend.
# =============================================================================

using XCALibre
using Accessors
using LinearAlgebra
using Printf
using Statistics

# ── 1. Mesh and Hardware ──────────────────────────────────────────────────────
# Pointing to the polyMesh directory generated by blockMesh in the OpenFOAM case.
mesh_dir = "/Volumes/OpenFOAM/mixed_viscoelasticity/openfoam_cases/stokes3plus3_bend/viscoelasticChannelBend_stokes_compressibleSolid_KelvinVoigt/constant/polyMesh"
mesh     = FOAM3D_mesh(mesh_dir, scale=1.0)

backend   = CPU(); workgroup = 1024
hardware  = Hardware(backend=backend, workgroup=workgroup)
mesh_dev  = adapt(backend, mesh)

# ── 2. Parameters ─────────────────────────────────────────────────────────────
mu_val  = 1.0
force_x = 1.0
force_y = 1.0  # Unitary force in both X and Y to drive flow around the bend
tau_rc  = 0.1

@info "Stokes Bend Benchmark: mu=$mu_val, force=($force_x, $force_y)"

# ── 3. Fields ─────────────────────────────────────────────────────────────────
u = ScalarField(mesh_dev); initialise!(u, 0.0)
v = ScalarField(mesh_dev); initialise!(v, 0.0)
p = ScalarField(mesh_dev); initialise!(p, 0.0)

# ── 4. Boundary Conditions ───────────────────────────────────────────────────
# BC names from blockMeshDict: inlet, outlet, walls, frontAndBack
BCs = assign(
    region = mesh_dev,
    (
        u = [Dirichlet(:walls, 0.0), Zerogradient(:inlet), Zerogradient(:outlet), Symmetry(:frontAndBack)],
        v = [Dirichlet(:walls, 0.0), Zerogradient(:inlet), Zerogradient(:outlet), Symmetry(:frontAndBack)],
        p = [Zerogradient(:walls), Zerogradient(:inlet), Zerogradient(:outlet), Symmetry(:frontAndBack)],
    )
)

# ── 5. Solver Setup ───────────────────────────────────────────────────────────
solvers = (
    u = SolverSetup(solver=Gmres(), preconditioner=Jacobi(), convergence=1e-10, relax=1.0),
    v = SolverSetup(solver=Gmres(), preconditioner=Jacobi(), convergence=1e-10, relax=1.0),
    p = SolverSetup(solver=Gmres(), preconditioner=Jacobi(), convergence=1e-10, relax=1.0),
)
config = Configuration(solvers=solvers, schemes=(u=Schemes(), v=Schemes(), p=Schemes()),
                       runtime=Runtime(iterations=1, write_interval=-1, time_step=1.0), hardware=hardware, boundaries=BCs)

# ── 6. Equations ──────────────────────────────────────────────────────────────
mu_cst    = ConstantScalar(mu_val)
one_cst   = ConstantScalar(1.0)
tau_rc_cst = ConstantScalar(tau_rc)

L_u = ((- Laplacian{Linear}(mu_cst) + ScalarGrad{Linear,1}(one_cst, p) == Source(force_x)) → BCs.u) → solvers.u
L_v = ((- Laplacian{Linear}(mu_cst) + ScalarGrad{Linear,2}(one_cst, p) == Source(force_y)) → BCs.v) → solvers.v
L_p = ((- Laplacian{Linear}(tau_rc_cst) + VectorDiv{Linear,1}(one_cst, u) + VectorDiv{Linear,2}(one_cst, v) == Source(0.0)) → BCs.p) → solvers.p

sys = MonolithicSystem([L_u(u), L_v(v), L_p(p)], [u, v, p])

# ── 7. Solve ──────────────────────────────────────────────────────────────────
@info "Solving Stokes Bend system..."
setReference!(sys.equations[3], 0.0, 1, config)
res = solve_monolithic!(sys, (BCs.u, BCs.v, BCs.p), config)
@info "Residual: $res, max|u|: $(maximum(abs.(u.values)))"
@info "Benchmark stokes_bend finished."
